phases:

################################################################################
- phase: build_windows_agent
################################################################################
  steps:
  - script: set

################################################################################
- phase: build_linux_agent
################################################################################
  steps:
  - checkout: self
  - script: set

################################################################################
- phase: build_osx_agent
################################################################################
  steps:
  - checkout: none
  - script: set
